### ISSUE TITLE
[IN-F3] Доска объявления

### ISSUE THREAD

**Issue by QviNSteN** [Insomnia-IT/intronet-front#3]
Необходимо создать страницу с отображением доски объявлений. 

Список, с кратким описанием и датой публикации.

При клике на отдельное объявление, открывается её полное описание.
Учесть пейджинг страниц.

**Comment by Corvus278** [comment]
На данный момент объявления отображаются без пейджинга, просто все на одной странице. По хорошему надо сделать пейджинг, в идеале infinity scroll
