### ISSUE TITLE
[IN-F0] Необходимо создать базовый фронт.

### ISSUE THREAD

**Issue by QviNSteN** [Insomnia-IT/intronet-front#5]
Необходимо реализовать базовое наполнение репозитория, для дальнейшей разработки.

Стартовую страницу, меню, базовую архитектуру для дальнейшего упрощения работы.

CSS файлики с цветами и тэдэ

Увы у нас всё по нулям щас

**Comment by franzzua** [comment]
Фуф, давайте немного обсудим тут.
Предлагаю следующий стек:
* typescript
* react (обычный, последней версии, через create-react-app)
* react-router
* [bulma](https://couds.github.io/react-bulma-components/?path=/docs/core-component-basics--page) для компонентов и стилизации. Совсем чуть-чуть с ней работал и в кастомизации она ок. 
* [cellx](https://github.com/Riim/cellx-react) для управления состоянием, простая как внутри так и снаружи.
* [storybook](https://storybook.js.org) для тестирования компонентов 
* [luxon](https://moment.github.io/luxon/#/) для работы с датавременем
* service-worker я с работы скопирую код

Если есть другие предложения, давайте обсуждать сейчас, все легко поменять сейчас, но сложно ближе к июлю.

**Comment by cherepanov** [comment]
кто за VUE? на нем будет быстрее. nuxt + vue3
сейчас переношу приложение на offline-web на vue

CRA - ненужно, могу быстро накопипастить шаблон со всеми плюшками

react-router - сложно и неудобно, v6 вообще рукаладонь. wouter нам хватит

css-фреймворк ненужн для внешних страниц.
для внутренних если брать то сразу компонентную библиотеку, тотже MUI и ANT
можно посмотреть на tailwind и headless ui

стейт менеджер ненужен. но если брать голосую за любой где поработал https://github.com/dai-shi

тестирование нафиг, никто кроме нас туда смотреть не будет. только для своего удовольствия

dayjs тоже неплох

для чего SW? их отлаживать геморойно, профит только на большом масштабе

**Comment by cherepanov** [comment]
давайте монорепу?

**Comment by franzzua** [comment]
* vue не умею, не хочу учить
* CRA должно хватить, а шаблон руками дорабатывать, но ок, давай.
* wouter ок
* mui ок. bulma тоже компонентый фреймворк
* стейт-менеджер. Тоже думал сначала, что и без него справимся, но вроде расписание и объявления надо будет хранить и обновлять
* storybook тестирование прост удобно для разработки, отдельно компоненты с моками рисовать-дебажить, пока апи сырое или не готово.
* dayjs плагины на каждый чих, если сможешь собрать нужное, то давай его, ок.
* SW нужен, у нас offline-first, перед экраном интернета нету, а голосовать хочется. 

Монорепу на lerna? А зачем, один ведь сайт, не?

**Comment by Radagant** [comment]
> кто за VUE? на нем будет быстрее. nuxt + vue3 сейчас переношу приложение на offline-web на vue

У меня больше опыта со вью, так что я за него руками и ногами. Если мнения прям сильно разделятся, то можем разделить фреймворки на два проекта, хотя в дальнейшем это наверное будет геморно обновлять и поддерживать. По поводу других опций со своей скромной недоджуниорской позиции ничего не могу сказать, что скажете использовать, то и выучу )

**Comment by cherepanov** [comment]
Давайте кормежку на vue, расписания на реакте, потом сравним)

> * CRA должно хватить, а шаблон руками дорабатывать, но ок, давай.
next? на днях выложу наработки с последнего проекта

> * стейт-менеджер. Тоже думал сначала, что и без него справимся, но вроде расписание и объявления надо будет хранить и обновлять
умного фетчера хватит. swr, react-query, etc. даже просто контекст, проблем не будет.

> * storybook тестирование прост удобно для разработки, отдельно компоненты с моками рисовать-дебажить, пока апи сырое или не готово.
зачем отдельно компоненты тестить? у нас не комерческая разработка/ воткнул за 5минут какой json-server  и работай, тестирую сразу всё

> * dayjs плагины на каждый чих, если сможешь собрать нужное, то давай его, ок.
конфиг на все случаи жизни:

```
import 'dayjs/locale/ru';
import customParseFormat from 'dayjs/plugin/customParseFormat';
import dayjs from 'dayjs';
import dayOfYear from 'dayjs/plugin/dayOfYear';
import devHelper from 'dayjs/plugin/devHelper';
import duration from 'dayjs/plugin/duration';
import isoWeek from 'dayjs/plugin/isoWeek';
import relativeTime from 'dayjs/plugin/relativeTime';
import toObject from 'dayjs/plugin/toObject';
import utc from 'dayjs/plugin/utc';
import weekday from 'dayjs/plugin/weekday';

dayjs.locale('ru');
dayjs.extend(relativeTime);
dayjs.extend(customParseFormat);
dayjs.extend(dayOfYear);
dayjs.extend(isoWeek);
dayjs.extend(weekday);
dayjs.extend(duration);
dayjs.extend(toObject);
dayjs.extend(utc);

if (isDev) {
    dayjs.extend(devHelper);
}
```

> * SW нужен, у нас offline-first, перед экраном интернета нету, а голосовать хочется.
> 
отлично. если есть отлаженный код тащи.

> Монорепу на lerna? А зачем, один ведь сайт, не?
лерна жмур и только для фронта.  систему управления не обязательно.
можно сэкономить немного времени держа все вместе.
можно сделать по репе на проект.

**Comment by Corvus278** [comment]
Докину ещё немного про typescript - стоит ли его здесь использовать?
Обычно его тащат в достаточно большие проекты со сложной архитектурой на сколько я знаю, здесь же у нас всё не так масштабно, имеет ли он смысл?
Он ведь и неудобств много создаёт помимо удобств

**Comment by Radagant** [comment]
Хотелось бы ещё уточнить, что подразумевается под базовым фронтом? Когда определимся с технологиями, у нас будет какой-то пример с фигмы от дизайнеров, который нужно перенести, или как это должно будет выглядеть? Нет опыта разработки приложения прям с нуля, поэтому хотелось бы более конкретного тз )

**Comment by franzzua** [comment]
> Докину ещё немного про typescript - стоит ли его здесь использовать? Обычно его тащат в достаточно большие проекты со сложной архитектурой на сколько я знаю, здесь же у нас всё не так масштабно, имеет ли он смысл? Он ведь и неудобств много создаёт помимо удобств

Да не, его везде можно тащить, проблем не будет

**Comment by cherepanov** [comment]
> > Докину ещё немного про typescript - стоит ли его здесь использовать? Обычно его тащат в достаточно большие проекты со сложной архитектурой на сколько я знаю, здесь же у нас всё не так масштабно, имеет ли он смысл? Он ведь и неудобств много создаёт помимо удобств
> 
> Да не, его везде можно тащить, проблем не будет

Если без фанатизма сильно поможет в поддержке и рефакторинге. KISS  и будет счастье. Ну и немножко сахара радует
